### ISSUE TITLE
Incorrect navigation for dependencies page

### ISSUE THREAD

**Issue by iamleeg** [mulle-objc/De-Re-mulle-objc#6]
In the table of contents, clicking on `Features/+dependencies` navigates to [Porting unichar](https://mulle-objc.github.io/De-Re-mulle-objc/mydoc_class.html).

**Comment by mulle-nat** [comment]
Fixed the permalink there. Thanks for the feedback. Unfortunately the actual `+dependencies` hasn't been written. If you have questions just ask :)
